# Generated by Django 4.1.13 on 2023-12-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empid',
            new_name='CompanyId',
        ),
    ]
