# Generated by Django 4.1.13 on 2023-12-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_empid_employee_companyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='CompanyId',
            new_name='Company_Name',
        ),
    ]
